version: "2.3"

services:

  npm-install:
    image: ${DOCKER_IMAGE:-books-oauth2:npm-install}
    build:
      context: ./
      args:
        NODE_TAG: "${NODE_TAG:-16-slim}"
        RELEASE_ENV: "npm-install"
    command: "npm install"
    networks:
      - traefik
    volumes:
      - ./oauth2-adapter:/home/node/workspace

  local:
    image: ${DOCKER_IMAGE:-books-oauth2:local}
    build:
      context: ./
      args:
        NODE_TAG: "${NODE_TAG:-16-slim}"
        RELEASE_ENV: "local"
    networks:
      - default
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8080}:${HTTP_PORT:-8080}
    volumes:
      - ./oauth2-adapter:/home/node/workspace
      - ./.env:/home/node/workspace/.env
    command:
      - npm
      - start

  # useful to run a development server online
  dev:
    image: ${DOCKER_IMAGE:-books-oauth2:dev}
    build:
      context: ./
      args:
        NODE_TAG: "${NODE_TAG:-16-slim}"
        RELEASE_ENV: "dev"
    command:
      - npm
      - start
    networks:
      - traefik
    volumes:
      - ./oauth2-adapter:/home/node/workspace
      - ./.env:/home/node/workspace/.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=books-oauth2-dev${RELEASE_TAG:-}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT:-8080}"
      - "traefik.frontend.rule=Host:${PUBLIC_DOMAINS:-dev.books-oauth2.demo.approov.io}"

  # useful to test in localhost the staging, rc and prod releases
  test:
    image: ${DOCKER_IMAGE:-books-oauth2:test}
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        RELEASE_ENV: "test"
        BUILD_RELEASE_FROM: "${BUILD_RELEASE_FROM:-master}"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-80}:${HTTP_PORT:-80}
    networks:
      - default
    volumes:
      - ./.env:/home/node/app/.env

  staging:
    image: ${DOCKER_IMAGE:-books-oauth2:staging}
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        RELEASE_ENV: "staging"
        BUILD_RELEASE_FROM: "${BUILD_RELEASE_FROM:-master}"
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./.env:/home/node/app/.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=books-oauth2-staging${RELEASE_TAG:-}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT:-8080}"
      - "traefik.frontend.rule=Host:${PUBLIC_DOMAINS:-staging.books-oauth2.demo.approov.io}"

  rc:
    image: ${DOCKER_IMAGE:-books-oauth2:rc}
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        RELEASE_ENV: "rc"
        BUILD_RELEASE_FROM: "${BUILD_RELEASE_FROM:-master}"
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./.env:/home/node/app/.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=books-oauth2-rc${RELEASE_TAG:-}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT:-8080}"
      - "traefik.frontend.rule=Host:${PUBLIC_DOMAINS:-rc.books-oauth2.demo.approov.io}"

  prod:
    image: ${DOCKER_IMAGE:-books-oauth2:prod}
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        RELEASE_ENV: "prod"
        BUILD_RELEASE_FROM: "${BUILD_RELEASE_FROM:-master}"
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./.env:/home/node/app/.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=books-oauth2-prod"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT:-8080}"
      - "traefik.frontend.rule=Host:${PUBLIC_DOMAINS:-books-oauth2.demo.approov.io}"

networks:
  traefik:
    external: true
